{
 "title": "Linky",
 "time": { "from": "now/y", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "provider",
    "label": "Fournisseur",
    "query": "SHOW TAG VALUES FROM linky_rp.prices WITH KEY=\"provider\""
   },
   {
    "name": "offer_name",
    "label": "Offre",
    "query": "SHOW TAG VALUES FROM linky_rp.prices WITH KEY=\"offer_name\" WHERE provider='${provider}'"
   },
   {
    "name": "offer_type",
    "label": "Type",
    "query": "SHOW TAG VALUES FROM linky_rp.prices WITH KEY=\"offer_type\" WHERE provider='${provider}' AND offer_name='${offer_name}'"
   }
  ]
 },
 "panels": [
  {
   "title": "${provider} (${offer_name}/${offer_type})",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "prices",
     "query": "SELECT time, last(ESTIMATED_COST) FROM linky_rp.prices",
     "select": [
      [
       { "params": [ "time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Facture actuelle",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Facture actuelle",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "linky",
     "query": "SELECT last(CURRENT_COST) FROM prices_mean WHERE provider='${provider}' AND offer_name='${offer_name}' AND offer_type='${offer_type}'",
     "select": [
      [
       { "params": [ "CURRENT_COST" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Facture now",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "linky",
     "query": "SELECT last(ESTIMATED_COST) - first(ESTIMATED_COST) FROM prices_mean WHERE time > now() - 1d and provider='${provider}' AND offer_name='${offer_name}' AND offer_type='${offer_type}'",
     "select": [
      [
       { "params": [ "ESTIMATED_COST" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Facture estimée",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Facture estimée",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "linky",
     "query": "SELECT last(ESTIMATED_COST) FROM prices_mean WHERE provider='${provider}' AND offer_name='${offer_name}' AND offer_type='${offer_type}'",
     "select": [
      [
       { "params": [ "ESTIMATED_COST" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heures pleines",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heures pleines",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "linky",
     "query": "SELECT last(HCHP) / 1000 FROM linky_rp.linky",
     "select": [
      [
       { "params": [ "HCHP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heures creuses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heures creuses",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "linky",
     "query": "SELECT last(HCHC) / 1000 FROM linky_rp.linky",
     "select": [
      [
       { "params": [ "HCHC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Puissance instantanée",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "W" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Puissance instantanée",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "linky",
     "query": "SELECT last(PAPP) FROM linky_rp.linky",
     "select": [
      [
       { "params": [ "PAPP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Puissance instantanée",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Puissance",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "linky",
     "query": "SELECT last(\"PAPP\") FROM \"linky\" WHERE $timeFilter GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "PAPP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Puissance moyenne historique",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "W" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Puissance moyenne année",
     "groupBy": [
      { "params": [ "365d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "linky",
     "query": "SELECT mean(PAPP) FROM linky_mean WHERE $timeFilter",
     "select": [
      [
       { "params": [ "PAPP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historique puissance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Puissance",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "linky_mean",
     "select": [
      [
       { "params": [ "PAPP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Répartition HP/HC",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "linky_mean",
     "query": "SELECT last(\"HCHP\") - first(\"HCHP\") AS HP, last(\"HCHC\") - first(\"HCHC\") as HC FROM \"linky_mean\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HCHC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ],
      [
       { "params": [ "HCHP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historique factures",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "month_number" ], "type": "tag" }
     ],
     "measurement": "prices",
     "query": "SELECT month_name, year_number, last(ESTIMATED_COST) FROM prices_mean WHERE provider='${provider}' AND year_number != '' AND offer_name='${offer_name}' AND offer_type='${offer_type}' GROUP BY month_number, year_number  ORDER BY time",
     "select": [
      [
       { "params": [ "CURRENT_COST" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Factures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "alias": "$tag_month_number/$tag_year_number",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(ESTIMATED_COST) FROM prices_mean WHERE provider='${provider}' AND $timeFilter AND year_number != '' AND offer_name='${offer_name}' AND offer_type='${offer_type}' GROUP BY year_number, month_number ORDER BY time ASC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Comparateur des offres électricité",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 20 },
   "targets": [
    {
     "alias": "$tag_provider ($tag_offer_name / $tag_offer_type)",
     "groupBy": [
      { "params": [ "provider" ], "type": "tag" },
      { "params": [ "offer_name" ], "type": "tag" },
      { "params": [ "offer_type" ], "type": "tag" }
     ],
     "measurement": "prices",
     "query": "SELECT last(ESTIMATED_COST) FROM prices_mean GROUP BY provider, offer_name, offer_type",
     "select": [
      [
       { "params": [ "ESTIMATED_COST" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}