###############################################################################
# InfluxDB backup/restore secrets
###############################################################################
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-backup-restore-secrets
type: Opaque
stringData:
  CIFS_PATH: //192.168.1.100/my_backup_dir
  CIFS_USERNAME: admin
  CIFS_PASSWORD: password
